version: "3.9"

services:
  loki:
    image: grafana/loki:2.9.4
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - loki-data:/loki
      - ./monitoring/loki-config.yaml:/etc/loki/local-config.yaml:ro
    command: -config.file=/etc/loki/local-config.yaml
    restart: always

  promtail:
    image: grafana/promtail:2.9.4
    container_name: promtail
    volumes:
      - ./monitoring/promtail-config.yaml:/etc/promtail/config.yml:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro # baca docker json logs
      - /var/log:/var/log:ro # opsional host logs (linux)
      - C:/Migrasi/Logs:/logs/win:ro # jika pakai Docker Desktop on Windows
    command: -config.file=/etc/promtail/config.yml
    restart: always

  grafana:
    image: grafana/grafana:9.5.0
    container_name: grafana
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - grafana-storage:/var/lib/grafana

volumes:
  loki-data:
  grafana-storage:
