// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Repositories.DbContexts;

#nullable disable

namespace Repositories.Migrations
{
    [DbContext(typeof(BleTrackingDbContext))]
    [Migration("20260212120000_PatrolApprovalV2")]
    partial class PatrolApprovalV2
    {
    }
}
